from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class HealthResponse(BaseModel):
    """Schema for health check endpoint response."""
    status: str = Field(..., description="API operational status (e.g. 'ok')")
    environment: str = Field(..., description="Current running environment configuration")
    database_connected: bool = Field(..., description="Indicator of database availability")

class UploadResponse(BaseModel):
    """Schema for document upload response."""
    message: str = Field(..., description="Response summary message")
    document_id: str = Field(..., description="Unique generated hash/ID of the document")
    filename: str = Field(..., description="Name of the uploaded PDF file")
    total_chunks: int = Field(..., description="Total text chunks ingested")
    file_hash: str = Field(..., description="SHA-256 hash value of the file content for deduplication")

class QueryRequest(BaseModel):
    """Schema for query/retrieval request body."""
    question: str = Field(..., description="The query string to be answered by the RAG model")
    top_k: Optional[int] = Field(None, description="Overrides default retrieval count of source chunks")
    metadata_filter: Optional[Dict[str, Any]] = Field(None, description="Metadata filtering criteria for ChromaDB query")

class Citation(BaseModel):
    """Schema for source chunk citation."""
    filename: str = Field(..., description="Name of the source document")
    page: int = Field(..., description="Page number where the chunk was extracted (1-indexed)")
    text: str = Field(..., description="The chunk text snippet used as context")

class QueryResponse(BaseModel):
    """Schema for query/retrieval response body."""
    answer: str = Field(..., description="Answer generated by the Gemini model")
    citations: List[Citation] = Field(..., description="Context chunks referenced in the response")
    latency_ms: float = Field(..., description="Time taken to run retrieval and generation in milliseconds")

class DocumentMetadata(BaseModel):
    """Schema representing metadata details of a stored document."""
    document_id: str = Field(..., description="ID/Hash of the document")
    filename: str = Field(..., description="Filename of the PDF source")
    file_hash: str = Field(..., description="SHA-256 hash value of the document")
    total_chunks: int = Field(..., description="Number of text chunks created from this document")
    upload_time: str = Field(..., description="ISO formatted upload timestamp")

class DocumentListResponse(BaseModel):
    """Schema for listing stored documents response."""
    documents: List[DocumentMetadata] = Field(..., description="List of all unique ingested documents")

class DeleteResponse(BaseModel):
    """Schema for document deletion response."""
    message: str = Field(..., description="Status description of the delete operation")
    success: bool = Field(..., description="Boolean indicating success status")
